[GD-109] Rework swithing network
Ankr-network/game-unity-sdk pull request #38
Opened 2022-05-19 08:02 UTC by sidorovkirill

2022-05-19 15:04 UTC, Vukiz requested changes

2022-05-19 15:04 UTC, Vukiz commented on Assets/AnkrSDK/Scripts/Mobile/AnkrNetworkHelper.cs
> +//			Application.OpenURL(url);
meaningless comments are not allowed, also this method does nothing, but it should, right?

2022-05-20 07:07 UTC, sidorovkirill commented on Assets/AnkrSDK/Examples/UseCases/AddSwitchNetwork/EthereumNetworks.cs
> +		public static EthereumNetwork GetSimpleNetwork(int chainId)
Cahnged to CreateMetamaskExistedNetwork

2022-05-20 07:11 UTC, sidorovkirill commented on Assets/AnkrSDK/Scripts/Data/EthereumNetwork.cs
> +	public class NativeCurrency
This class don't need without EthereumNetwork

2022-05-20 07:26 UTC, sidorovkirill commented on Assets/AnkrSDK/Scripts/Data/NetworkName.cs
> -		Ethereum_Ropsten_TestNet,
Of course it's a testnets, but those names well-known, and otherwice we have test nets that duplicate original nets. And in that case I think we need to mark it like _TestNet. But not in the case of well-known test networks.

2022-05-20 09:36 UTC, Vukiz requested changes

2022-05-20 09:36 UTC, Vukiz commented on Assets/AnkrSDK/Scripts/Data/EthereumNetwork.cs
> +	public class NativeCurrency
Does not matter if it is public it shouldn't be inside file with another class

2022-05-20 09:36 UTC, Vukiz commented on Assets/AnkrSDK/Scripts/Mobile/AnkrNetworkHelper.cs
> +		private static void AddAndSwitchCustomNetwork(string url)
don't make it private

2022-05-20 11:56 UTC, sidorovkirill commented on .idea/.idea.game-unity-sdk/.idea/indexLayout.xml
> +  <component name="ContentModelUserStore">
It's already there

2022-05-20 12:00 UTC, Vukiz commented on .idea/.idea.game-unity-sdk/.idea/indexLayout.xml
> +  <component name="ContentModelUserStore">
Well then you should remove it from index then

2022-05-20 12:18 UTC, Vukiz approved these changes

2022-05-20 12:30 UTC, merged